set -e

case "$1" in
        purge)

        rm -f /var/lib/openli/provauth.db
        rm -f /etc/openli/provauthdb.phrase
        rm -f /etc/openli/.intercept-encrypt
        rm -f /etc/openli/*.yaml

        ;;
        remove|upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
        ;;

        *)
        echo "postrm called with unknown argument \`$1'" >&2
        exit 1
        ;;
esac

#DEBHELPER#

exit 0
