name: Packaging for RPM

on:
  push:
    tags:
      - '*'

jobs:
  build:
     runs-on: ubuntu-latest
     container:
       image: ${{ matrix.target }}
     strategy:
       fail-fast: false
       matrix:
         arch:
           - amd64
         target:
           - "rockylinux:8"
           - "rockylinux:9"
           - "fedora:39"
           - "fedora:38"

     steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Install prereq packages
        run: ./rpmpkg-setup.sh ${{ matrix.target }}
      - name: Build packages
        run: ./rpmpkg-build.sh
      - name: Set environment variables for upload
        run: echo DIRNAME=${{ matrix.target }} | tr ':' '_' >> $GITHUB_ENV
      - name: Copy packages to uploadable location
        run: |
          mkdir -p packages/${DIRNAME}
          cp ~/rpmbuild/RPMS/x86_64/*.rpm packages/${DIRNAME}/
      - name: Store packages
        uses: actions/upload-artifact@v4
        with:
          name: packages-${{ env.DIRNAME }}
          path: packages/${{ env.DIRNAME }}/*.rpm
          retention-days: 1

  test:
     runs-on: ubuntu-latest
     container:
       image: ${{ matrix.target }}
     strategy:
       fail-fast: false
       matrix:
         arch:
           - amd64
         target:
           - "rockylinux:8"
           - "rockylinux:9"
           - "fedora:39"
           - "fedora:38"
     needs: build
     steps:
       - name: Set environment variables for download
         run: echo DIRNAME=${{ matrix.target }} | tr ':' '_' >> $GITHUB_ENV
       - name: Download artifact
         uses: actions/download-artifact@v4
         with:
           name: packages-${{ env.DIRNAME }}
       - name: Add repositories
         env:
           TARGET: ${{ matrix.target }}
         run: |
           curl -1sLf 'https://dl.cloudsmith.io/public/wand/libwandio/cfg/setup/bash.rpm.sh' | bash
           curl -1sLf 'https://dl.cloudsmith.io/public/wand/libwandder/cfg/setup/bash.rpm.sh' | bash
           curl -1sLf 'https://dl.cloudsmith.io/public/wand/libtrace/cfg/setup/bash.rpm.sh' | bash
           curl -1sLf 'https://dl.cloudsmith.io/public/wand/openli/cfg/setup/bash.rpm.sh' | bash
           curl -1sLf https://packagecloud.io/rabbitmq/rabbitmq-server/gpgkey -o packagecloud-rabbitmq-key.asc
           gpg --import packagecloud-rabbitmq-key.asc
           curl -s https://packagecloud.io/install/repositories/rabbitmq/rabbitmq-server/script.rpm.sh | bash
           curl -s https://packagecloud.io/install/repositories/rabbitmq/erlang/script.rpm.sh | bash
           if [[ "${TARGET}" =~ rocky* ]]; then
               dnf install -y dnf-plugins-core epel-release || true
               dnf config-manager --set-enabled powertools || true
               /usr/bin/crb enable || true
           fi
       - name: Test package install
         run: |
           yum install -y findutils
           find . -name "*.rpm" | xargs yum install -y
       - name: Test package removal
         run: |
           rpm -e openli-provisioner
           rpm -e openli-collector
           rpm -e openli-mediator


  publish:
     runs-on: ubuntu-latest
     container:
       image: ${{ matrix.target }}
     strategy:
       fail-fast: false
       matrix:
         arch:
           - amd64
         target:
           - "rockylinux:8"
           - "rockylinux:9"
           - "fedora:39"
           - "fedora:38"
     needs: test
     steps:
       - name: Set environment variables for download
         run: echo DIRNAME=${{ matrix.target }} | tr ':' '_' >> $GITHUB_ENV
       - name: Download artifact
         uses: actions/download-artifact@v4
         with:
           name: packages-${{ env.DIRNAME }}
       - name: Copy packages
         run: |
           mkdir -p packages/${DIRNAME}
           yum install -y findutils
           find . -name "*.rpm" | xargs cp -t packages/${DIRNAME}/
       - name: Publish package to cloudsmith
         uses: salcock/action-cloudsmith-upload-packages@v1.8
         with:
           path: packages/
           repo: ${{ secrets.CLOUDSMITH_OWNER }}/openli
           username: salcock
           api_key: ${{ secrets.CLOUDSMITH_API_KEY }}



